apiVersion: v1
kind: Secret
metadata:
  name: vma-secret
  namespace: default
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://shivanshdubey746:Shivansh%40%23123@cluster0.pvubgoi.mongodb.net/?appName=Cluster0"
  OHLC_MONGO_URI: "mongodb+srv://Avneesh:Avneesh%4012345@cluster0.sqcsrv2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "supersecretkey"
  ANGEL_API_KEY: "6HaMJD5F"
  ANGEL_CLIENT_ID: "AABY903828"
  ANGEL_MPIN: "1975"
  ANGEL_TOTP_SECRET: "OM5E5K7T4MKB6QUQLX2CACIGNY"
