apiVersion: v1
kind: Service
metadata:
  name: vma-algo-service
  namespace: default
  labels:
    app: vma-algo
spec:
  type: NodePort  # Change to LoadBalancer or ClusterIP if using Ingress Controller
  selector:
    app: vma-algo
  ports:
  - port: 8024
    targetPort: 8024
    nodePort: 30024  # Exposed on node IP at port 30024
    name: http
